Importando biblioteca Pandas

In [23]:
import pandas as pd

Acessando e lendo a Planilha

In [22]:
df = pd.read_csv("/museums.csv")

/tmp/ipykernel_8405/92981825.py:1: DtypeWarning: Columns (9,14,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/museums.csv")

Identificando a quantidade de (dados) Linhas e Colunas que vamos trabalhar

In [ ]:
df.shape

(33072, 25)

Listando o nome das Colunas

In [ ]:
df.columns

Index(['Museum ID', 'Museum Name', 'Legal Name', 'Alternate Name',
       'Museum Type', 'Institution Name',
       'Street Address (Administrative Location)',
       'City (Administrative Location)', 'State (Administrative Location)',
       'Zip Code (Administrative Location)',
       'Street Address (Physical Location)', 'City (Physical Location)',
       'State (Physical Location)', 'Zip Code (Physical Location)',
       'Phone Number', 'Latitude', 'Longitude', 'Locale Code (NCES)',
       'County Code (FIPS)', 'State Code (FIPS)', 'Region Code (AAM)',
       'Employer ID Number', 'Tax Period', 'Income', 'Revenue'],
      dtype='object')

Identificando o tipo de cada coluna

In [ ]:
df.dtypes

Museum ID                                     int64
Museum Name                                  object
Legal Name                                   object
Alternate Name                               object
Museum Type                                  object
Institution Name                             object
Street Address (Administrative Location)     object
City (Administrative Location)               object
State (Administrative Location)              object
Zip Code (Administrative Location)           object
Street Address (Physical Location)           object
City (Physical Location)                     object
State (Physical Location)                    object
Zip Code (Physical Location)                float64
Phone Number                                 object
Latitude                                    float64
Longitude                                   float64
Locale Code (NCES)                          float64
County Code (FIPS)                          float64
State Code (FIPS)                           float64
Region Code (AAM)                             int64
Employer ID Number                           object
Tax Period                                  float64
Income                                      float64
Revenue                                     float64
dtype: object

Calculando quantos valores estão faltando por coluna

In [ ]:
df.isnull().sum()

Museum ID                                       0
Museum Name                                     0
Legal Name                                      0
Alternate Name                              31145
Museum Type                                     0
Institution Name                            30323
Street Address (Administrative Location)       10
City (Administrative Location)                  0
State (Administrative Location)                 0
Zip Code (Administrative Location)              0
Street Address (Physical Location)          23856
City (Physical Location)                    23849
State (Physical Location)                   23849
Zip Code (Physical Location)                23851
Phone Number                                10140
Latitude                                       65
Longitude                                      65
Locale Code (NCES)                             77
County Code (FIPS)                           2536
State Code (FIPS)                               1
Region Code (AAM)                               0
Employer ID Number                           5518
Tax Period                                   9792
Income                                      10111
Revenue                                     10782
dtype: int64

Vericando a porcentagem de valores nulos de cada coluna

In [ ]:
df.isnull().sum()/len(df)*100

Museum ID                                    0.000000
Museum Name                                  0.000000
Legal Name                                   0.000000
Alternate Name                              94.173319
Museum Type                                  0.000000
Institution Name                            91.687833
Street Address (Administrative Location)     0.030237
City (Administrative Location)               0.000000
State (Administrative Location)              0.000000
Zip Code (Administrative Location)           0.000000
Street Address (Physical Location)          72.133527
City (Physical Location)                    72.112361
State (Physical Location)                   72.112361
Zip Code (Physical Location)                72.118408
Phone Number                                30.660377
Latitude                                     0.196541
Longitude                                    0.196541
Locale Code (NCES)                           0.232825
County Code (FIPS)                           7.668118
State Code (FIPS)                            0.003024
Region Code (AAM)                            0.000000
Employer ID Number                          16.684809
Tax Period                                  29.608128
Income                                      30.572690
Revenue                                     32.601597
dtype: float64

Calculando estatísticas básicas

In [ ]:
df[["Income", "Revenue"]].describe()

             Income       Revenue
count  2.296100e+04  2.229000e+04
mean   1.069682e+08  2.097605e+07
std    2.509287e+09  2.485197e+08
min   -9.230000e+02 -2.127393e+06
25%    0.000000e+00  0.000000e+00
50%    8.781000e+03  3.307000e+03
75%    2.163770e+05  1.676960e+05
max    8.318144e+10  5.840349e+09

Verificando duplicatas exatas

In [ ]:
df.duplicated().sum()

np.int64(0)

Verificando duplicatas por nome (nome)

In [8]:
df["Museum Name"].duplicated().sum()

np.int64(1526)

Verificando duplicatas por nome (nome + cidade + estado)

In [9]:
df.duplicated(subset=["Museum Name", "City (Administrative Location)", "State (Administrative Location)"]).sum()

np.int64(96)

Verificando padrão de duplicatas por nome (nome + cidade + estado), ordenando a partir da coluna (Museum Name) e exibindo apenas colunas especificas

In [13]:
df[df.duplicated(subset=["Museum Name", "City (Administrative Location)", "State (Administrative Location)"], keep=False)].sort_values("Museum Name")[["Museum Name", "Legal Name", "Institution Name", "City (Administrative Location)", "State (Administrative Location)", "Revenue"]]

,Museum Name,Legal Name,Institution Name,City (Administrative Location),State (Administrative Location),Revenue
8231,ALBION VALLEY HISTORICAL SOCIETY,ALBION VALLEY HISTORICAL SOCIETY,NaN,ALBION,ID,NaN
8232,ALBION VALLEY HISTORICAL SOCIETY,ALBION VALLEY HISTORICAL SOCIETY INC,NaN,ALBION,ID,0.0
1513,ARMAND HAMMER MUSEUM OF ART AND CULTURAL CENTER,REGENTS UNIVERSITY OF CALIFORNIA LOS ANGELES,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",LOS ANGELES,CA,NaN
1512,ARMAND HAMMER MUSEUM OF ART AND CULTURAL CENTER,ARMAND HAMMER MUSEUM OF ART AND CULTURAL CENTE...,NaN,LOS ANGELES,CA,15183141.0
22333,BEDFORD HISTORICAL SOCIETY,BEDFORD HISTORICAL SOCIETY,NaN,BEDFORD,OH,NaN
...,...,...,...,...,...,...
24662,WASHINGTON COUNTY MUSEUM,WASHINGTON COUNTY MUSEUM,NaN,PORTLAND,OR,NaN
11414,WAYNE COUNTY HISTORICAL SOCIETY,WAYNE COUNTY HISTORICAL SOCIETY INC,NaN,MONTICELLO,KY,0.0
11415,WAYNE COUNTY HISTORICAL SOCIETY,MICHAEL J QUILL IRISH CULTURAL AND SPORTS CENT...,NaN,MONTICELLO,KY,434743.0
9705,WEST CHICAGO HISTORICAL SOCIETY,WEST CHICAGO HISTORICAL SOCIETY,NaN,WEST CHICAGO,IL,4646.0
9706,WEST CHICAGO HISTORICAL SOCIETY,WEST CHICAGO HISTORICAL SOCIETY,NaN,WEST CHICAGO,IL,4646.0

Adicionando o Legal Name na verificação de duplicadas

In [5]:
df.duplicated(subset=["Museum Name", "Legal Name", "City (Administrative Location)", "State (Administrative Location)"]).sum()

np.int64(54)

Verificando se o 0 é informado ou não informado (valor real declarado)

In [16]:
df[df["Revenue"] == 0][["Tax Period", "Income"]].isnull().sum()

Tax Period    0
Income        0
dtype: int64

Contando campos preenchidos por linha

In [24]:
df["completude"] = df.notna().sum(axis=1)

Fazendo analise da coluna completude

In [25]:
df["completude"].describe()

count    33072.000000
mean        18.772073
std          2.575637
min          9.000000
25%         18.000000
50%         19.000000
75%         20.000000
max         24.000000
Name: completude, dtype: float64

Isolando os duplicados

In [26]:
duplicados = df[df.duplicated(subset=["Museum Name", "Legal Name", "City (Administrative Location)", "State (Administrative Location)"], keep=False)]

Fazendo Analise dos duplicados

In [27]:
duplicados["completude"].describe()

count    108.000000
mean      20.009259
std        2.613750
min       15.000000
25%       19.000000
50%       19.000000
75%       23.000000
max       24.000000
Name: completude, dtype: float64

Verificando valores da Tax Period

In [28]:
df["Tax Period"].head(10)

0    201312.0
1    201312.0
2    201312.0
3    201412.0
4    201312.0
5         NaN
6    201312.0
7    201312.0
8    201406.0
9    201412.0
Name: Tax Period, dtype: float64

Ordenando dando prioridade a maior completude

In [30]:
df_ordenado = df.sort_values(by=["completude","Revenue","Tax Period"], ascending=[False, False, False])